name: gin-boilerplate
mode: dev
listen:
  https: true
  port: 8888
  certFile: server.crt
  keyFile: server.key
db:
  dialect: sqlite3
  dns: sqlite.db
smtp:
  addr: smtp.qq.com:25
  username: 2637309949@qq.com
  identity:
  password: jhprqpetmlfteabe
  host: smtp.qq.com