info:
  contact: {}
  license: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: home index
      produces:
      - application/json
      summary: Index
      tags:
      - index
  /api/v1/deleteArticle:
    post:
      consumes:
      - application/json
      description: delete article
      produces:
      - application/json
      summary: DeleteArticle
      tags:
      - articles
  /api/v1/deleteOptionset:
    post:
      consumes:
      - application/json
      description: delete optionset
      produces:
      - application/json
      summary: DeleteOptionset
      tags:
      - optionsets
  /api/v1/insertArticle:
    post:
      consumes:
      - application/json
      description: new article
      produces:
      - application/json
      summary: InsertArticle
      tags:
      - articles
  /api/v1/insertOptionset:
    post:
      consumes:
      - application/json
      description: new article
      produces:
      - application/json
      summary: InsertOptionset
      tags:
      - optionsets
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: user login
      produces:
      - application/json
      summary: Login
      tags:
      - users
  /api/v1/logout:
    post:
      consumes:
      - application/json
      description: user logout
      produces:
      - application/json
      summary: Logout
      tags:
      - users
  /api/v1/queryArticle:
    get:
      consumes:
      - application/json
      description: get article by gived params
      parameters:
      - description: page no
        in: query
        name: page_no
        required: true
        type: integer
      - description: page size
        in: query
        name: page_size
        required: true
        type: integer
      - description: order type
        in: query
        name: order_type
        required: true
        type: integer
      - description: order col
        in: query
        name: order_col
        required: true
        type: integer
      produces:
      - application/json
      summary: QueryArticle
      tags:
      - articles
  /api/v1/queryArticleDetail:
    get:
      consumes:
      - application/json
      description: get article by gived id
      produces:
      - application/json
      summary: QueryArticleDetail
      tags:
      - articles
  /api/v1/queryOptionset:
    get:
      consumes:
      - application/json
      description: get optionset by give params
      parameters:
      - description: page no
        in: query
        name: page_no
        required: true
        type: integer
      - description: page size
        in: query
        name: page_size
        required: true
        type: integer
      - description: order type
        in: query
        name: order_type
        required: true
        type: integer
      - description: order col
        in: query
        name: order_col
        required: true
        type: integer
      produces:
      - application/json
      summary: QueryOptionset
      tags:
      - optionsets
  /api/v1/queryOptionsetDetail:
    get:
      consumes:
      - application/json
      description: get optionset by gived id
      produces:
      - application/json
      summary: QueryOptionsetDetail
      tags:
      - optionsets
  /api/v1/refresh:
    post:
      consumes:
      - application/json
      description: refresh token
      produces:
      - application/json
      summary: Refresh
      tags:
      - tokens
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: user register
      produces:
      - application/json
      summary: Register
      tags:
      - users
  /api/v1/resetPassword:
    post:
      consumes:
      - application/json
      description: reset password
      produces:
      - application/json
      summary: ResetPassword
      tags:
      - users
  /api/v1/sendPasswordResetEmail:
    post:
      consumes:
      - application/json
      description: send password reset email
      produces:
      - application/json
      summary: SendPasswordResetEmail
      tags:
      - users
  /api/v1/sendVerificationEmail:
    post:
      consumes:
      - application/json
      description: send verification email
      produces:
      - application/json
      summary: SendVerificationEmail
      tags:
      - users
  /api/v1/updateArticle:
    post:
      consumes:
      - application/json
      description: update article
      produces:
      - application/json
      summary: UpdateArticle
      tags:
      - articles
  /api/v1/updateOptionset:
    post:
      consumes:
      - application/json
      description: update optionset
      produces:
      - application/json
      summary: UpdateOptionset
      tags:
      - optionsets
  /api/v1/updatePassword:
    post:
      consumes:
      - application/json
      description: user updatePassword
      produces:
      - application/json
      summary: Logout
      tags:
      - users
  /api/v1/verifyEmail:
    post:
      consumes:
      - application/json
      description: verify email
      produces:
      - application/json
      summary: VerifyEmail
      tags:
      - users
securityDefinitions:
  "":
    authorizationUrl: ""
    flow: accessCode
    scopes:
      admin: ""
      read: ""
      write: ""
    type: oauth2
    x-tokenName: Authorization
swagger: "2.0"
