info:
  contact: {}
  license: {}
paths:
  /api/v1/DeleteArticle:
    post:
      consumes:
      - application/json
      description: delete article
      produces:
      - application/json
      summary: DeleteArticle
      tags:
      - articles
  /api/v1/DeleteOptionset:
    post:
      consumes:
      - application/json
      description: delete optionset
      produces:
      - application/json
      summary: DeleteOptionset
      tags:
      - optionsets
  /api/v1/InsertArticle:
    post:
      consumes:
      - application/json
      description: new article
      produces:
      - application/json
      summary: InsertArticle
      tags:
      - articles
  /api/v1/InsertOptionset:
    post:
      consumes:
      - application/json
      description: new article
      produces:
      - application/json
      summary: InsertOptionset
      tags:
      - optionsets
  /api/v1/QueryArticle:
    get:
      consumes:
      - application/json
      description: get article by gived params
      parameters:
      - description: page no
        in: query
        name: page_no
        required: true
        type: integer
      - description: page size
        in: query
        name: page_size
        required: true
        type: integer
      - description: order type
        in: query
        name: order_type
        required: true
        type: integer
      - description: order col
        in: query
        name: order_col
        required: true
        type: integer
      produces:
      - application/json
      summary: QueryArticle
      tags:
      - articles
  /api/v1/QueryArticleDetail:
    get:
      consumes:
      - application/json
      description: get article by gived id
      produces:
      - application/json
      summary: QueryArticleDetail
      tags:
      - articles
  /api/v1/QueryOptionset:
    get:
      consumes:
      - application/json
      description: get optionset by give params
      parameters:
      - description: page no
        in: query
        name: page_no
        required: true
        type: integer
      - description: page size
        in: query
        name: page_size
        required: true
        type: integer
      - description: order type
        in: query
        name: order_type
        required: true
        type: integer
      - description: order col
        in: query
        name: order_col
        required: true
        type: integer
      produces:
      - application/json
      summary: QueryOptionset
      tags:
      - optionsets
  /api/v1/UpdateArticle:
    post:
      consumes:
      - application/json
      description: update article
      produces:
      - application/json
      summary: UpdateArticle
      tags:
      - articles
  /api/v1/UpdateOptionset:
    post:
      consumes:
      - application/json
      description: update optionset
      produces:
      - application/json
      summary: UpdateOptionset
      tags:
      - optionsets
securityDefinitions:
  "":
    authorizationUrl: ""
    flow: accessCode
    scopes:
      admin: ""
      read: ""
      write: ""
    type: oauth2
    x-tokenName: Authorization
swagger: "2.0"
